/* dbus_server.c generated by valac 0.28.1, the Vala compiler
 * generated from dbus_server.vala, do not modify */

/* Note: this attribute specifies the _interface_ name.  It
 * is called 'name =' for historical reasons.
 */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define TYPE_DBUS_SERVER (dbus_server_get_type ())
#define DBUS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DBUS_SERVER, DbusServer))
#define DBUS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DBUS_SERVER, DbusServerClass))
#define IS_DBUS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DBUS_SERVER))
#define IS_DBUS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DBUS_SERVER))
#define DBUS_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DBUS_SERVER, DbusServerClass))

typedef struct _DbusServer DbusServer;
typedef struct _DbusServerClass DbusServerClass;
typedef struct _DbusServerPrivate DbusServerPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _DbusServer {
	GObject parent_instance;
	DbusServerPrivate * priv;
};

struct _DbusServerClass {
	GObjectClass parent_class;
};

struct _DbusServerPrivate {
	gint counter;
};

typedef enum  {
	DEMO_ERROR_SOME_ERROR
} DemoError;
#define DEMO_ERROR demo_error_quark ()

static gpointer dbus_server_parent_class = NULL;

GType dbus_server_get_type (void) G_GNUC_CONST;
guint dbus_server_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
#define DBUS_SERVER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_DBUS_SERVER, DbusServerPrivate))
enum  {
	DBUS_SERVER_DUMMY_PROPERTY
};
gint dbus_server_ping (DbusServer* self, const gchar* msg);
gint dbus_server_ping_with_signal (DbusServer* self, const gchar* msg);
gint dbus_server_ping_with_sender (DbusServer* self, const gchar* msg, const char* sender);
void dbus_server_ping_error (DbusServer* self, GError** error);
GQuark demo_error_quark (void);
DbusServer* dbus_server_new (void);
DbusServer* dbus_server_construct (GType object_type);
static void g_cclosure_user_marshal_VOID__INT_STRING (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void dbus_server_finalize (GObject* obj);
static void _dbus_dbus_server_ping (DbusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation);
static void _dbus_dbus_server_ping_with_signal (DbusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation);
static void _dbus_dbus_server_ping_with_sender (DbusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation);
static void _dbus_dbus_server_ping_error (DbusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation);
static void dbus_server_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* dbus_server_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean dbus_server_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _dbus_dbus_server_on_message (GObject* _sender, const gchar* verify, gpointer* _data);
static void _dbus_dbus_server_pong (GObject* _sender, gint count, const gchar* msg, gpointer* _data);
static void _dbus_server_unregister_object (gpointer user_data);

static const GDBusArgInfo _dbus_server_dbus_arg_info_ping_msg = {-1, "msg", "s"};
static const GDBusArgInfo _dbus_server_dbus_arg_info_ping_result = {-1, "result", "i"};
static const GDBusArgInfo * const _dbus_server_dbus_arg_info_ping_in[] = {&_dbus_server_dbus_arg_info_ping_msg, NULL};
static const GDBusArgInfo * const _dbus_server_dbus_arg_info_ping_out[] = {&_dbus_server_dbus_arg_info_ping_result, NULL};
static const GDBusMethodInfo _dbus_server_dbus_method_info_ping = {-1, "Ping", (GDBusArgInfo **) (&_dbus_server_dbus_arg_info_ping_in), (GDBusArgInfo **) (&_dbus_server_dbus_arg_info_ping_out)};
static const GDBusArgInfo _dbus_server_dbus_arg_info_ping_with_signal_msg = {-1, "msg", "s"};
static const GDBusArgInfo _dbus_server_dbus_arg_info_ping_with_signal_result = {-1, "result", "i"};
static const GDBusArgInfo * const _dbus_server_dbus_arg_info_ping_with_signal_in[] = {&_dbus_server_dbus_arg_info_ping_with_signal_msg, NULL};
static const GDBusArgInfo * const _dbus_server_dbus_arg_info_ping_with_signal_out[] = {&_dbus_server_dbus_arg_info_ping_with_signal_result, NULL};
static const GDBusMethodInfo _dbus_server_dbus_method_info_ping_with_signal = {-1, "PingWithSignal", (GDBusArgInfo **) (&_dbus_server_dbus_arg_info_ping_with_signal_in), (GDBusArgInfo **) (&_dbus_server_dbus_arg_info_ping_with_signal_out)};
static const GDBusArgInfo _dbus_server_dbus_arg_info_ping_with_sender_msg = {-1, "msg", "s"};
static const GDBusArgInfo _dbus_server_dbus_arg_info_ping_with_sender_result = {-1, "result", "i"};
static const GDBusArgInfo * const _dbus_server_dbus_arg_info_ping_with_sender_in[] = {&_dbus_server_dbus_arg_info_ping_with_sender_msg, NULL};
static const GDBusArgInfo * const _dbus_server_dbus_arg_info_ping_with_sender_out[] = {&_dbus_server_dbus_arg_info_ping_with_sender_result, NULL};
static const GDBusMethodInfo _dbus_server_dbus_method_info_ping_with_sender = {-1, "PingWithSender", (GDBusArgInfo **) (&_dbus_server_dbus_arg_info_ping_with_sender_in), (GDBusArgInfo **) (&_dbus_server_dbus_arg_info_ping_with_sender_out)};
static const GDBusArgInfo * const _dbus_server_dbus_arg_info_ping_error_in[] = {NULL};
static const GDBusArgInfo * const _dbus_server_dbus_arg_info_ping_error_out[] = {NULL};
static const GDBusMethodInfo _dbus_server_dbus_method_info_ping_error = {-1, "PingError", (GDBusArgInfo **) (&_dbus_server_dbus_arg_info_ping_error_in), (GDBusArgInfo **) (&_dbus_server_dbus_arg_info_ping_error_out)};
static const GDBusMethodInfo * const _dbus_server_dbus_method_info[] = {&_dbus_server_dbus_method_info_ping, &_dbus_server_dbus_method_info_ping_with_signal, &_dbus_server_dbus_method_info_ping_with_sender, &_dbus_server_dbus_method_info_ping_error, NULL};
static const GDBusArgInfo _dbus_server_dbus_arg_info_on_message_verify = {-1, "verify", "s"};
static const GDBusArgInfo * const _dbus_server_dbus_arg_info_on_message[] = {&_dbus_server_dbus_arg_info_on_message_verify, NULL};
static const GDBusSignalInfo _dbus_server_dbus_signal_info_on_message = {-1, "onMessage", (GDBusArgInfo **) (&_dbus_server_dbus_arg_info_on_message)};
static const GDBusArgInfo _dbus_server_dbus_arg_info_pong_count = {-1, "count", "i"};
static const GDBusArgInfo _dbus_server_dbus_arg_info_pong_msg = {-1, "msg", "s"};
static const GDBusArgInfo * const _dbus_server_dbus_arg_info_pong[] = {&_dbus_server_dbus_arg_info_pong_count, &_dbus_server_dbus_arg_info_pong_msg, NULL};
static const GDBusSignalInfo _dbus_server_dbus_signal_info_pong = {-1, "Pong", (GDBusArgInfo **) (&_dbus_server_dbus_arg_info_pong)};
static const GDBusSignalInfo * const _dbus_server_dbus_signal_info[] = {&_dbus_server_dbus_signal_info_on_message, &_dbus_server_dbus_signal_info_pong, NULL};
static const GDBusPropertyInfo * const _dbus_server_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _dbus_server_dbus_interface_info = {-1, "org.gzen_money.Demo", (GDBusMethodInfo **) (&_dbus_server_dbus_method_info), (GDBusSignalInfo **) (&_dbus_server_dbus_signal_info), (GDBusPropertyInfo **) (&_dbus_server_dbus_property_info)};
static const GDBusInterfaceVTable _dbus_server_dbus_interface_vtable = {dbus_server_dbus_interface_method_call, dbus_server_dbus_interface_get_property, dbus_server_dbus_interface_set_property};
static const GDBusErrorEntry demo_error_entries[] = {{DEMO_ERROR_SOME_ERROR, "org.gzen_money.DemoError.SomeError"}};

gint dbus_server_ping (DbusServer* self, const gchar* msg) {
	gint result = 0;
	FILE* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (msg != NULL, 0);
	_tmp0_ = stdout;
	_tmp1_ = msg;
	fprintf (_tmp0_, "%s\n", _tmp1_);
	_tmp2_ = msg;
	g_signal_emit_by_name (self, "on-message", _tmp2_);
	_tmp3_ = self->priv->counter;
	self->priv->counter = _tmp3_ + 1;
	result = _tmp3_;
	return result;
}


gint dbus_server_ping_with_signal (DbusServer* self, const gchar* msg) {
	gint result = 0;
	FILE* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	const gchar* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (msg != NULL, 0);
	_tmp0_ = stdout;
	_tmp1_ = msg;
	fprintf (_tmp0_, "%s\n", _tmp1_);
	_tmp2_ = self->priv->counter;
	_tmp3_ = msg;
	g_signal_emit_by_name (self, "pong", _tmp2_, _tmp3_);
	_tmp4_ = self->priv->counter;
	self->priv->counter = _tmp4_ + 1;
	result = _tmp4_;
	return result;
}


gint dbus_server_ping_with_sender (DbusServer* self, const gchar* msg, const char* sender) {
	gint result = 0;
	FILE* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const char* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (msg != NULL, 0);
	g_return_val_if_fail (sender != NULL, 0);
	_tmp0_ = stdout;
	_tmp1_ = msg;
	_tmp2_ = sender;
	fprintf (_tmp0_, "%s, from: %s\n", _tmp1_, (const gchar*) _tmp2_);
	_tmp3_ = self->priv->counter;
	self->priv->counter = _tmp3_ + 1;
	result = _tmp3_;
	return result;
}


void dbus_server_ping_error (DbusServer* self, GError** error) {
	GError* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_error_new_literal (DEMO_ERROR, DEMO_ERROR_SOME_ERROR, "There was an error!");
	_inner_error_ = _tmp0_;
	g_propagate_error (error, _inner_error_);
	return;
}


DbusServer* dbus_server_construct (GType object_type) {
	DbusServer * self = NULL;
	self = (DbusServer*) g_object_new (object_type, NULL);
	return self;
}


DbusServer* dbus_server_new (void) {
	return dbus_server_construct (TYPE_DBUS_SERVER);
}


static void g_cclosure_user_marshal_VOID__INT_STRING (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__INT_STRING) (gpointer data1, gint arg_1, const char* arg_2, gpointer data2);
	register GMarshalFunc_VOID__INT_STRING callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__INT_STRING) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_int (param_values + 1), g_value_get_string (param_values + 2), data2);
}


static void dbus_server_class_init (DbusServerClass * klass) {
	dbus_server_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (DbusServerPrivate));
	G_OBJECT_CLASS (klass)->finalize = dbus_server_finalize;
	g_signal_new ("on_message", TYPE_DBUS_SERVER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
	g_signal_new ("pong", TYPE_DBUS_SERVER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__INT_STRING, G_TYPE_NONE, 2, G_TYPE_INT, G_TYPE_STRING);
}


static void dbus_server_instance_init (DbusServer * self) {
	self->priv = DBUS_SERVER_GET_PRIVATE (self);
}


static void dbus_server_finalize (GObject* obj) {
	DbusServer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DBUS_SERVER, DbusServer);
	G_OBJECT_CLASS (dbus_server_parent_class)->finalize (obj);
}


GType dbus_server_get_type (void) {
	static volatile gsize dbus_server_type_id__volatile = 0;
	if (g_once_init_enter (&dbus_server_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DbusServerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dbus_server_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DbusServer), 0, (GInstanceInitFunc) dbus_server_instance_init, NULL };
		GType dbus_server_type_id;
		dbus_server_type_id = g_type_register_static (G_TYPE_OBJECT, "DbusServer", &g_define_type_info, 0);
		g_type_set_qdata (dbus_server_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) dbus_server_register_object);
		g_once_init_leave (&dbus_server_type_id__volatile, dbus_server_type_id);
	}
	return dbus_server_type_id__volatile;
}


static void _dbus_dbus_server_ping (DbusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* msg = NULL;
	GVariant* _tmp0_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	_tmp0_ = g_variant_iter_next_value (&_arguments_iter);
	msg = g_variant_dup_string (_tmp0_, NULL);
	g_variant_unref (_tmp0_);
	result = dbus_server_ping (self, msg);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (msg);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_dbus_server_ping_with_signal (DbusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* msg = NULL;
	GVariant* _tmp1_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	_tmp1_ = g_variant_iter_next_value (&_arguments_iter);
	msg = g_variant_dup_string (_tmp1_, NULL);
	g_variant_unref (_tmp1_);
	result = dbus_server_ping_with_signal (self, msg);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (msg);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_dbus_server_ping_with_sender (DbusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* msg = NULL;
	GVariant* _tmp2_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gint result;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	_tmp2_ = g_variant_iter_next_value (&_arguments_iter);
	msg = g_variant_dup_string (_tmp2_, NULL);
	g_variant_unref (_tmp2_);
	result = dbus_server_ping_with_sender (self, msg, g_dbus_method_invocation_get_sender (invocation));
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_int32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (msg);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_dbus_server_ping_error (DbusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	dbus_server_ping_error (self, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void dbus_server_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "Ping") == 0) {
		_dbus_dbus_server_ping (object, parameters, invocation);
	} else if (strcmp (method_name, "PingWithSignal") == 0) {
		_dbus_dbus_server_ping_with_signal (object, parameters, invocation);
	} else if (strcmp (method_name, "PingWithSender") == 0) {
		_dbus_dbus_server_ping_with_sender (object, parameters, invocation);
	} else if (strcmp (method_name, "PingError") == 0) {
		_dbus_dbus_server_ping_error (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* dbus_server_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean dbus_server_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


static void _dbus_dbus_server_on_message (GObject* _sender, const gchar* verify, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (verify));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.gzen_money.Demo", "onMessage", _arguments, NULL);
}


static void _dbus_dbus_server_pong (GObject* _sender, gint count, const gchar* msg, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_int32 (count));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (msg));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.gzen_money.Demo", "Pong", _arguments, NULL);
}


guint dbus_server_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_dbus_server_dbus_interface_info), &_dbus_server_dbus_interface_vtable, data, _dbus_server_unregister_object, error);
	if (!result) {
		return 0;
	}
	g_signal_connect (object, "on-message", (GCallback) _dbus_dbus_server_on_message, data);
	g_signal_connect (object, "pong", (GCallback) _dbus_dbus_server_pong, data);
	return result;
}


static void _dbus_server_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_signal_handlers_disconnect_by_func (data[0], _dbus_dbus_server_on_message, data);
	g_signal_handlers_disconnect_by_func (data[0], _dbus_dbus_server_pong, data);
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


GQuark demo_error_quark (void) {
	static volatile gsize demo_error_quark_volatile = 0;
	g_dbus_error_register_error_domain ("demo_error-quark", &demo_error_quark_volatile, demo_error_entries, G_N_ELEMENTS (demo_error_entries));
	return (GQuark) demo_error_quark_volatile;
}



