/* oauth-zenmoney.c generated by valac 0.28.1, the Vala compiler
 * generated from oauth-zenmoney.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <libsoup/soup.h>
#include <gobject/gvaluecollector.h>


#define TYPE_OAUTH_ZENMONEY (oauth_zenmoney_get_type ())
#define OAUTH_ZENMONEY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OAUTH_ZENMONEY, OauthZenmoney))
#define OAUTH_ZENMONEY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_OAUTH_ZENMONEY, OauthZenmoneyClass))
#define IS_OAUTH_ZENMONEY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OAUTH_ZENMONEY))
#define IS_OAUTH_ZENMONEY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_OAUTH_ZENMONEY))
#define OAUTH_ZENMONEY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_OAUTH_ZENMONEY, OauthZenmoneyClass))

typedef struct _OauthZenmoney OauthZenmoney;
typedef struct _OauthZenmoneyClass OauthZenmoneyClass;
typedef struct _OauthZenmoneyPrivate OauthZenmoneyPrivate;

#define OAUTH_TYPE_CLIENT (oauth_client_get_type ())
#define OAUTH_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OAUTH_TYPE_CLIENT, OAuthClient))
#define OAUTH_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OAUTH_TYPE_CLIENT, OAuthClientClass))
#define OAUTH_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OAUTH_TYPE_CLIENT))
#define OAUTH_IS_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OAUTH_TYPE_CLIENT))
#define OAUTH_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OAUTH_TYPE_CLIENT, OAuthClientClass))

typedef struct _OAuthClient OAuthClient;
typedef struct _OAuthClientClass OAuthClientClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define OAUTH_TYPE_HMAC_SHA1 (oauth_hmac_sha1_get_type ())
#define OAUTH_HMAC_SHA1(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OAUTH_TYPE_HMAC_SHA1, OAuthHMAC_SHA1))
#define OAUTH_HMAC_SHA1_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OAUTH_TYPE_HMAC_SHA1, OAuthHMAC_SHA1Class))
#define OAUTH_IS_HMAC_SHA1(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OAUTH_TYPE_HMAC_SHA1))
#define OAUTH_IS_HMAC_SHA1_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OAUTH_TYPE_HMAC_SHA1))
#define OAUTH_HMAC_SHA1_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OAUTH_TYPE_HMAC_SHA1, OAuthHMAC_SHA1Class))

typedef struct _OAuthHMAC_SHA1 OAuthHMAC_SHA1;
typedef struct _OAuthHMAC_SHA1Class OAuthHMAC_SHA1Class;

#define OAUTH_TYPE_ISIGNATURE_METHOD (oauth_isignature_method_get_type ())
#define OAUTH_ISIGNATURE_METHOD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OAUTH_TYPE_ISIGNATURE_METHOD, OAuthISignatureMethod))
#define OAUTH_IS_ISIGNATURE_METHOD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OAUTH_TYPE_ISIGNATURE_METHOD))
#define OAUTH_ISIGNATURE_METHOD_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), OAUTH_TYPE_ISIGNATURE_METHOD, OAuthISignatureMethodIface))

typedef struct _OAuthISignatureMethod OAuthISignatureMethod;
typedef struct _OAuthISignatureMethodIface OAuthISignatureMethodIface;
#define __vala_SoupBuffer_free0(var) ((var == NULL) ? NULL : (var = (_vala_SoupBuffer_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _ParamSpecOauthZenmoney ParamSpecOauthZenmoney;

struct _OauthZenmoney {
	GTypeInstance parent_instance;
	volatile int ref_count;
	OauthZenmoneyPrivate * priv;
};

struct _OauthZenmoneyClass {
	GTypeClass parent_class;
	void (*finalize) (OauthZenmoney *self);
};

struct _OauthZenmoneyPrivate {
	OAuthClient* client;
	gchar* token;
};

struct _OAuthISignatureMethodIface {
	GTypeInterface parent_iface;
	gchar* (*sign) (OAuthISignatureMethod* self, const gchar* token_secret, const gchar* sig_base);
	gchar* (*to_string) (OAuthISignatureMethod* self);
};

typedef enum  {
	OAUTH_ERROR_INVALID_ARGUMENT
} OAuthError;
#define OAUTH_ERROR oauth_error_quark ()
struct _ParamSpecOauthZenmoney {
	GParamSpec parent_instance;
};


static gpointer oauth_zenmoney_parent_class = NULL;

#define REALM ""
#define KEY "215923636aa71c72ca3431990e5ff0"
#define SECRET "fab63a4738"
#define REQUEST_TOKEN_URL "http://api.zenmoney.ru/oauth/request_token"
#define REQUEST_AUTHORIZE_URL "http://api.zenmoney.ru/access/?oauth_callback='gzen-pass://verify'&oau" \
"th_token=%s"
#define ACCESS_TOKEN_URL "http://api.zenmoney.ru/oauth/access_token"
gpointer oauth_zenmoney_ref (gpointer instance);
void oauth_zenmoney_unref (gpointer instance);
GParamSpec* param_spec_oauth_zenmoney (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_oauth_zenmoney (GValue* value, gpointer v_object);
void value_take_oauth_zenmoney (GValue* value, gpointer v_object);
gpointer value_get_oauth_zenmoney (const GValue* value);
GType oauth_zenmoney_get_type (void) G_GNUC_CONST;
GType oauth_client_get_type (void) G_GNUC_CONST;
#define OAUTH_ZENMONEY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_OAUTH_ZENMONEY, OauthZenmoneyPrivate))
enum  {
	OAUTH_ZENMONEY_DUMMY_PROPERTY
};
OauthZenmoney* oauth_zenmoney_new (void);
OauthZenmoney* oauth_zenmoney_construct (GType object_type);
OAuthHMAC_SHA1* oauth_hmac_sha1_new (const gchar* secret);
OAuthHMAC_SHA1* oauth_hmac_sha1_construct (GType object_type, const gchar* secret);
GType oauth_hmac_sha1_get_type (void) G_GNUC_CONST;
GType oauth_isignature_method_get_type (void) G_GNUC_CONST;
OAuthClient* oauth_client_new (const gchar* realm, const gchar* oauth_consumer_key, OAuthISignatureMethod* sigmeth);
OAuthClient* oauth_client_construct (GType object_type, const gchar* realm, const gchar* oauth_consumer_key, OAuthISignatureMethod* sigmeth);
void oauth_zenmoney_init (OauthZenmoney* self, const gchar* token, const gchar* token_secret);
void oauth_client_set_token (OAuthClient* self, const gchar* oauth_token, const gchar* oauth_token_secret);
void oauth_zenmoney_getAccessToken_A (OauthZenmoney* self);
GeeMap* oauth_client_request_token (OAuthClient* self, const gchar* http_method, const gchar* request_endpoint_uri, const gchar* oauth_callback);
static void _vala_SoupBuffer_free (SoupBuffer* self);
GQuark oauth_error_quark (void);
gchar* oauth_client_auth_token (OAuthClient* self, const gchar* auth_endpoint_uri_template, const gchar* oauth_token, const gchar* oauth_token_secret, const gchar* oauth_callback_confirmed, GError** error);
GeeMap* oauth_zenmoney_getAccessToken_B (OauthZenmoney* self, const gchar* pin);
GeeMap* oauth_client_access_token (OAuthClient* self, const gchar* http_method, const gchar* access_endpoint_uri, const gchar* oauth_token, const gchar* oauth_verifier, GError** error);
SoupMessage* oauth_zenmoney_Auth (OauthZenmoney* self, const gchar* method, const gchar* url, GeeMultiMap* parameters);
GeeMap* oauth_client_authenticate (OAuthClient* self, const gchar* http_method, const gchar* uri, GeeMultiMap* args_);
static void oauth_zenmoney_finalize (OauthZenmoney* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


OauthZenmoney* oauth_zenmoney_construct (GType object_type) {
	OauthZenmoney* self = NULL;
	OAuthHMAC_SHA1* _tmp0_ = NULL;
	OAuthHMAC_SHA1* _tmp1_ = NULL;
	OAuthClient* _tmp2_ = NULL;
	self = (OauthZenmoney*) g_type_create_instance (object_type);
	g_message ("oauth-zenmoney.vala:19: Creating instance of new Oauth client");
	_tmp0_ = oauth_hmac_sha1_new (SECRET);
	_tmp1_ = _tmp0_;
	_tmp2_ = oauth_client_new (REALM, KEY, (OAuthISignatureMethod*) _tmp1_);
	_g_object_unref0 (self->priv->client);
	self->priv->client = _tmp2_;
	_g_object_unref0 (_tmp1_);
	return self;
}


OauthZenmoney* oauth_zenmoney_new (void) {
	return oauth_zenmoney_construct (TYPE_OAUTH_ZENMONEY);
}


void oauth_zenmoney_init (OauthZenmoney* self, const gchar* token, const gchar* token_secret) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	OAuthClient* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (token != NULL);
	g_return_if_fail (token_secret != NULL);
	_tmp0_ = token;
	_tmp1_ = token_secret;
	g_message ("oauth-zenmoney.vala:24: Setting token: %s , %s", _tmp0_, _tmp1_);
	_tmp2_ = self->priv->client;
	_tmp3_ = token;
	_tmp4_ = token_secret;
	oauth_client_set_token (_tmp2_, _tmp3_, _tmp4_);
}


static void _vala_SoupBuffer_free (SoupBuffer* self) {
	g_boxed_free (soup_buffer_get_type (), self);
}


void oauth_zenmoney_getAccessToken_A (OauthZenmoney* self) {
	static const char method[] = "POST";
	static const char callback[] = "oob";
	GeeMap* request = NULL;
	OAuthClient* _tmp0_ = NULL;
	GeeMap* _tmp1_ = NULL;
	gchar* request_auth = NULL;
	GeeMap* _tmp2_ = NULL;
	gpointer _tmp3_ = NULL;
	SoupSessionSync* session = NULL;
	SoupSessionSync* _tmp4_ = NULL;
	SoupMessage* smessage = NULL;
	SoupMessage* _tmp5_ = NULL;
	SoupMessage* _tmp6_ = NULL;
	SoupMessageHeaders* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	SoupSessionSync* _tmp9_ = NULL;
	SoupMessage* _tmp10_ = NULL;
	gchar* response = NULL;
	SoupMessage* _tmp11_ = NULL;
	SoupMessageBody* _tmp12_ = NULL;
	SoupBuffer* _tmp13_ = NULL;
	SoupBuffer* _tmp14_ = NULL;
	guint8* _tmp15_ = NULL;
	gint _tmp15__length1 = 0;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	const gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar** parts = NULL;
	const gchar* _tmp21_ = NULL;
	gchar** _tmp22_ = NULL;
	gchar** _tmp23_ = NULL;
	gint parts_length1 = 0;
	gint _parts_size_ = 0;
	gchar* token_secret = NULL;
	gchar* _tmp24_ = NULL;
	gchar** _tmp25_ = NULL;
	gint _tmp25__length1 = 0;
	const gchar* _tmp40_ = NULL;
	gchar* _tmp41_ = NULL;
	gchar* _tmp42_ = NULL;
	gchar* url = NULL;
	gchar* _tmp43_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_message ("oauth-zenmoney.vala:29: %s", "Getting access token for key: " KEY);
	_tmp0_ = self->priv->client;
	_tmp1_ = oauth_client_request_token (_tmp0_, method, REQUEST_TOKEN_URL, callback);
	_g_object_unref0 (request);
	request = _tmp1_;
	g_message ("oauth-zenmoney.vala:37: Preparing request");
	_tmp2_ = request;
	_tmp3_ = gee_map_get (_tmp2_, "Authorization");
	request_auth = (gchar*) _tmp3_;
	_tmp4_ = (SoupSessionSync*) soup_session_sync_new ();
	session = _tmp4_;
	_tmp5_ = soup_message_new (method, REQUEST_TOKEN_URL);
	smessage = _tmp5_;
	_tmp6_ = smessage;
	_tmp7_ = _tmp6_->request_headers;
	_tmp8_ = request_auth;
	soup_message_headers_append (_tmp7_, "Authorization", _tmp8_);
	_tmp9_ = session;
	_tmp10_ = smessage;
	soup_session_send_message ((SoupSession*) _tmp9_, _tmp10_);
	_tmp11_ = smessage;
	_tmp12_ = _tmp11_->response_body;
	_tmp13_ = soup_message_body_flatten (_tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = _tmp14_->data;
	_tmp15__length1 = (gint) _tmp14_->length;
	_tmp16_ = g_strdup ((const gchar*) _tmp15_);
	_tmp17_ = _tmp16_;
	__vala_SoupBuffer_free0 (_tmp14_);
	response = _tmp17_;
	_tmp18_ = response;
	_tmp19_ = g_strconcat ("Token response: ", _tmp18_, NULL);
	_tmp20_ = _tmp19_;
	g_message ("oauth-zenmoney.vala:46: %s", _tmp20_);
	_g_free0 (_tmp20_);
	_tmp21_ = response;
	_tmp23_ = _tmp22_ = g_strsplit (_tmp21_, "&", 0);
	parts = _tmp23_;
	parts_length1 = _vala_array_length (_tmp22_);
	_parts_size_ = parts_length1;
	_tmp24_ = g_strdup ("");
	token_secret = _tmp24_;
	_tmp25_ = parts;
	_tmp25__length1 = parts_length1;
	{
		gchar** part_collection = NULL;
		gint part_collection_length1 = 0;
		gint _part_collection_size_ = 0;
		gint part_it = 0;
		part_collection = _tmp25_;
		part_collection_length1 = _tmp25__length1;
		for (part_it = 0; part_it < _tmp25__length1; part_it = part_it + 1) {
			gchar* _tmp26_ = NULL;
			gchar* part = NULL;
			_tmp26_ = g_strdup (part_collection[part_it]);
			part = _tmp26_;
			{
				gchar** p = NULL;
				const gchar* _tmp27_ = NULL;
				gchar** _tmp28_ = NULL;
				gchar** _tmp29_ = NULL;
				gint p_length1 = 0;
				gint _p_size_ = 0;
				gchar** _tmp30_ = NULL;
				gint _tmp30__length1 = 0;
				const gchar* _tmp31_ = NULL;
				_tmp27_ = part;
				_tmp29_ = _tmp28_ = g_strsplit (_tmp27_, "=", 0);
				p = _tmp29_;
				p_length1 = _vala_array_length (_tmp28_);
				_p_size_ = p_length1;
				_tmp30_ = p;
				_tmp30__length1 = p_length1;
				_tmp31_ = _tmp30_[0];
				if (g_strcmp0 (_tmp31_, "oauth_token") == 0) {
					gchar** _tmp32_ = NULL;
					gint _tmp32__length1 = 0;
					const gchar* _tmp33_ = NULL;
					gchar* _tmp34_ = NULL;
					_tmp32_ = p;
					_tmp32__length1 = p_length1;
					_tmp33_ = _tmp32_[1];
					_tmp34_ = g_strdup (_tmp33_);
					_g_free0 (self->priv->token);
					self->priv->token = _tmp34_;
				} else {
					gchar** _tmp35_ = NULL;
					gint _tmp35__length1 = 0;
					const gchar* _tmp36_ = NULL;
					_tmp35_ = p;
					_tmp35__length1 = p_length1;
					_tmp36_ = _tmp35_[0];
					if (g_strcmp0 (_tmp36_, "oauth_token_secret") == 0) {
						gchar** _tmp37_ = NULL;
						gint _tmp37__length1 = 0;
						const gchar* _tmp38_ = NULL;
						gchar* _tmp39_ = NULL;
						_tmp37_ = p;
						_tmp37__length1 = p_length1;
						_tmp38_ = _tmp37_[1];
						_tmp39_ = g_strdup (_tmp38_);
						_g_free0 (token_secret);
						token_secret = _tmp39_;
					}
				}
				p = (_vala_array_free (p, p_length1, (GDestroyNotify) g_free), NULL);
				_g_free0 (part);
			}
		}
	}
	_tmp40_ = self->priv->token;
	_tmp41_ = g_strconcat ("Token catched:", _tmp40_, NULL);
	_tmp42_ = _tmp41_;
	g_message ("oauth-zenmoney.vala:59: %s", _tmp42_);
	_g_free0 (_tmp42_);
	_tmp43_ = g_strdup ("");
	url = _tmp43_;
	{
		gchar* _tmp44_ = NULL;
		OAuthClient* _tmp45_ = NULL;
		const gchar* _tmp46_ = NULL;
		const gchar* _tmp47_ = NULL;
		gchar* _tmp48_ = NULL;
		gchar* _tmp49_ = NULL;
		const gchar* _tmp50_ = NULL;
		gchar* _tmp51_ = NULL;
		gchar* _tmp52_ = NULL;
		_tmp45_ = self->priv->client;
		_tmp46_ = self->priv->token;
		_tmp47_ = token_secret;
		_tmp48_ = oauth_client_auth_token (_tmp45_, REQUEST_AUTHORIZE_URL, _tmp46_, _tmp47_, "true", &_inner_error_);
		_tmp44_ = _tmp48_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == OAUTH_ERROR) {
				goto __catch2_oauth_error;
			}
			_g_free0 (url);
			_g_free0 (token_secret);
			parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (response);
			_g_object_unref0 (smessage);
			_g_object_unref0 (session);
			_g_free0 (request_auth);
			_g_object_unref0 (request);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_tmp49_ = _tmp44_;
		_tmp44_ = NULL;
		_g_free0 (url);
		url = _tmp49_;
		_tmp50_ = url;
		_tmp51_ = g_strconcat ("Token URL:", _tmp50_, NULL);
		_tmp52_ = _tmp51_;
		g_message ("oauth-zenmoney.vala:64: %s", _tmp52_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp44_);
	}
	goto __finally2;
	__catch2_oauth_error:
	{
		GError* e = NULL;
		GError* _tmp53_ = NULL;
		const gchar* _tmp54_ = NULL;
		gchar* _tmp55_ = NULL;
		gchar* _tmp56_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp53_ = e;
		_tmp54_ = _tmp53_->message;
		_tmp55_ = g_strconcat ("Error: ", _tmp54_, NULL);
		_tmp56_ = _tmp55_;
		g_print ("%s", _tmp56_);
		_g_free0 (_tmp56_);
		_g_error_free0 (e);
	}
	__finally2:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (url);
		_g_free0 (token_secret);
		parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (response);
		_g_object_unref0 (smessage);
		_g_object_unref0 (session);
		_g_free0 (request_auth);
		_g_object_unref0 (request);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	{
		const gchar* _tmp57_ = NULL;
		gchar* _tmp58_ = NULL;
		gchar* _tmp59_ = NULL;
		const gchar* _tmp60_ = NULL;
		gchar* _tmp61_ = NULL;
		gchar* _tmp62_ = NULL;
		gchar* _tmp63_ = NULL;
		gchar* _tmp64_ = NULL;
		_tmp57_ = url;
		_tmp58_ = g_strconcat (_tmp57_, "\n", NULL);
		_tmp59_ = _tmp58_;
		g_print ("%s", _tmp59_);
		_g_free0 (_tmp59_);
		_tmp60_ = url;
		_tmp61_ = g_strconcat ("xdg-open '", _tmp60_, NULL);
		_tmp62_ = _tmp61_;
		_tmp63_ = g_strconcat (_tmp62_, "'", NULL);
		_tmp64_ = _tmp63_;
		g_spawn_command_line_async (_tmp64_, &_inner_error_);
		_g_free0 (_tmp64_);
		_g_free0 (_tmp62_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == G_SPAWN_ERROR) {
				goto __catch3_g_spawn_error;
			}
			_g_free0 (url);
			_g_free0 (token_secret);
			parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (response);
			_g_object_unref0 (smessage);
			_g_object_unref0 (session);
			_g_free0 (request_auth);
			_g_object_unref0 (request);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally3;
	__catch3_g_spawn_error:
	{
		GError* e = NULL;
		GError* _tmp65_ = NULL;
		const gchar* _tmp66_ = NULL;
		gchar* _tmp67_ = NULL;
		gchar* _tmp68_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp65_ = e;
		_tmp66_ = _tmp65_->message;
		_tmp67_ = g_strconcat ("Error: ", _tmp66_, NULL);
		_tmp68_ = _tmp67_;
		g_print ("%s", _tmp68_);
		_g_free0 (_tmp68_);
		_g_error_free0 (e);
	}
	__finally3:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (url);
		_g_free0 (token_secret);
		parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (response);
		_g_object_unref0 (smessage);
		_g_object_unref0 (session);
		_g_free0 (request_auth);
		_g_object_unref0 (request);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_free0 (url);
	_g_free0 (token_secret);
	parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (response);
	_g_object_unref0 (smessage);
	_g_object_unref0 (session);
	_g_free0 (request_auth);
	_g_object_unref0 (request);
}


GeeMap* oauth_zenmoney_getAccessToken_B (OauthZenmoney* self, const gchar* pin) {
	GeeMap* result = NULL;
	static const char method[] = "POST";
	GeeMap* access = NULL;
	GeeHashMap* _tmp0_ = NULL;
	gchar* access_auth = NULL;
	GeeMap* _tmp11_ = NULL;
	gpointer _tmp12_ = NULL;
	SoupSessionSync* session = NULL;
	SoupSessionSync* _tmp13_ = NULL;
	SoupMessage* message = NULL;
	SoupMessage* _tmp14_ = NULL;
	SoupMessage* _tmp15_ = NULL;
	SoupMessageHeaders* _tmp16_ = NULL;
	const gchar* _tmp17_ = NULL;
	SoupSessionSync* _tmp18_ = NULL;
	SoupMessage* _tmp19_ = NULL;
	gchar** parts = NULL;
	SoupMessage* _tmp20_ = NULL;
	SoupMessageBody* _tmp21_ = NULL;
	guint8* _tmp22_ = NULL;
	gint _tmp22__length1 = 0;
	gchar** _tmp23_ = NULL;
	gchar** _tmp24_ = NULL;
	gint parts_length1 = 0;
	gint _parts_size_ = 0;
	SoupMessage* _tmp25_ = NULL;
	SoupMessageBody* _tmp26_ = NULL;
	guint8* _tmp27_ = NULL;
	gint _tmp27__length1 = 0;
	gchar* token = NULL;
	gchar* _tmp28_ = NULL;
	gchar* token_secret = NULL;
	gchar* _tmp29_ = NULL;
	gchar** _tmp30_ = NULL;
	gint _tmp30__length1 = 0;
	OAuthClient* _tmp45_ = NULL;
	const gchar* _tmp46_ = NULL;
	const gchar* _tmp47_ = NULL;
	GeeHashMap* ret = NULL;
	GeeHashMap* _tmp48_ = NULL;
	const gchar* _tmp49_ = NULL;
	const gchar* _tmp50_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (pin != NULL, NULL);
	_tmp0_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	access = (GeeMap*) _tmp0_;
	{
		GeeMap* _tmp1_ = NULL;
		OAuthClient* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		GeeMap* _tmp5_ = NULL;
		GeeMap* _tmp6_ = NULL;
		_tmp2_ = self->priv->client;
		_tmp3_ = self->priv->token;
		_tmp4_ = pin;
		_tmp5_ = oauth_client_access_token (_tmp2_, method, ACCESS_TOKEN_URL, _tmp3_, _tmp4_, &_inner_error_);
		_tmp1_ = _tmp5_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == OAUTH_ERROR) {
				goto __catch4_oauth_error;
			}
			_g_object_unref0 (access);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp6_ = _tmp1_;
		_tmp1_ = NULL;
		_g_object_unref0 (access);
		access = _tmp6_;
		_g_object_unref0 (_tmp1_);
	}
	goto __finally4;
	__catch4_oauth_error:
	{
		GError* e = NULL;
		GError* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp7_ = e;
		_tmp8_ = _tmp7_->message;
		_tmp9_ = g_strconcat ("Error: ", _tmp8_, NULL);
		_tmp10_ = _tmp9_;
		g_print ("%s", _tmp10_);
		_g_free0 (_tmp10_);
		_g_error_free0 (e);
	}
	__finally4:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (access);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp11_ = access;
	_tmp12_ = gee_map_get (_tmp11_, "Authorization");
	access_auth = (gchar*) _tmp12_;
	_tmp13_ = (SoupSessionSync*) soup_session_sync_new ();
	session = _tmp13_;
	_tmp14_ = soup_message_new (method, ACCESS_TOKEN_URL);
	message = _tmp14_;
	_tmp15_ = message;
	_tmp16_ = _tmp15_->request_headers;
	_tmp17_ = access_auth;
	soup_message_headers_append (_tmp16_, "Authorization", _tmp17_);
	_tmp18_ = session;
	_tmp19_ = message;
	soup_session_send_message ((SoupSession*) _tmp18_, _tmp19_);
	_tmp20_ = message;
	_tmp21_ = _tmp20_->response_body;
	_tmp22_ = _tmp21_->data;
	_tmp22__length1 = (gint) _tmp21_->length;
	_tmp24_ = _tmp23_ = g_strsplit ((const gchar*) _tmp22_, "&", 0);
	parts = _tmp24_;
	parts_length1 = _vala_array_length (_tmp23_);
	_parts_size_ = parts_length1;
	_tmp25_ = message;
	_tmp26_ = _tmp25_->response_body;
	_tmp27_ = _tmp26_->data;
	_tmp27__length1 = (gint) _tmp26_->length;
	g_warning ("oauth-zenmoney.vala:96: %s", (const gchar*) _tmp27_);
	_tmp28_ = g_strdup ("");
	token = _tmp28_;
	_tmp29_ = g_strdup ("");
	token_secret = _tmp29_;
	_tmp30_ = parts;
	_tmp30__length1 = parts_length1;
	{
		gchar** part_collection = NULL;
		gint part_collection_length1 = 0;
		gint _part_collection_size_ = 0;
		gint part_it = 0;
		part_collection = _tmp30_;
		part_collection_length1 = _tmp30__length1;
		for (part_it = 0; part_it < _tmp30__length1; part_it = part_it + 1) {
			gchar* _tmp31_ = NULL;
			gchar* part = NULL;
			_tmp31_ = g_strdup (part_collection[part_it]);
			part = _tmp31_;
			{
				gchar** p = NULL;
				const gchar* _tmp32_ = NULL;
				gchar** _tmp33_ = NULL;
				gchar** _tmp34_ = NULL;
				gint p_length1 = 0;
				gint _p_size_ = 0;
				gchar** _tmp35_ = NULL;
				gint _tmp35__length1 = 0;
				const gchar* _tmp36_ = NULL;
				_tmp32_ = part;
				_tmp34_ = _tmp33_ = g_strsplit (_tmp32_, "=", 0);
				p = _tmp34_;
				p_length1 = _vala_array_length (_tmp33_);
				_p_size_ = p_length1;
				_tmp35_ = p;
				_tmp35__length1 = p_length1;
				_tmp36_ = _tmp35_[0];
				if (g_strcmp0 (_tmp36_, "oauth_token") == 0) {
					gchar** _tmp37_ = NULL;
					gint _tmp37__length1 = 0;
					const gchar* _tmp38_ = NULL;
					gchar* _tmp39_ = NULL;
					_tmp37_ = p;
					_tmp37__length1 = p_length1;
					_tmp38_ = _tmp37_[1];
					_tmp39_ = g_strdup (_tmp38_);
					_g_free0 (token);
					token = _tmp39_;
				} else {
					gchar** _tmp40_ = NULL;
					gint _tmp40__length1 = 0;
					const gchar* _tmp41_ = NULL;
					_tmp40_ = p;
					_tmp40__length1 = p_length1;
					_tmp41_ = _tmp40_[0];
					if (g_strcmp0 (_tmp41_, "oauth_token_secret") == 0) {
						gchar** _tmp42_ = NULL;
						gint _tmp42__length1 = 0;
						const gchar* _tmp43_ = NULL;
						gchar* _tmp44_ = NULL;
						_tmp42_ = p;
						_tmp42__length1 = p_length1;
						_tmp43_ = _tmp42_[1];
						_tmp44_ = g_strdup (_tmp43_);
						_g_free0 (token_secret);
						token_secret = _tmp44_;
					}
				}
				p = (_vala_array_free (p, p_length1, (GDestroyNotify) g_free), NULL);
				_g_free0 (part);
			}
		}
	}
	_tmp45_ = self->priv->client;
	_tmp46_ = token;
	_tmp47_ = token_secret;
	oauth_client_set_token (_tmp45_, _tmp46_, _tmp47_);
	_tmp48_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	ret = _tmp48_;
	_tmp49_ = token;
	gee_abstract_map_set ((GeeAbstractMap*) ret, "consumer_key", _tmp49_);
	_tmp50_ = token_secret;
	gee_abstract_map_set ((GeeAbstractMap*) ret, "consumer_secret", _tmp50_);
	result = (GeeMap*) ret;
	_g_free0 (token_secret);
	_g_free0 (token);
	parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (message);
	_g_object_unref0 (session);
	_g_free0 (access_auth);
	_g_object_unref0 (access);
	return result;
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	glong string_length = 0L;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	glong _tmp2_ = 0L;
	glong _tmp5_ = 0L;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_ = 0L;
	gboolean _tmp12_ = FALSE;
	glong _tmp13_ = 0L;
	glong _tmp16_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	gchar* _tmp21_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	_tmp2_ = start;
	if (_tmp2_ < ((glong) 0)) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		_tmp3_ = string_length;
		_tmp4_ = start;
		start = _tmp3_ + _tmp4_;
	}
	_tmp5_ = end;
	if (_tmp5_ < ((glong) 0)) {
		glong _tmp6_ = 0L;
		glong _tmp7_ = 0L;
		_tmp6_ = string_length;
		_tmp7_ = end;
		end = _tmp6_ + _tmp7_;
	}
	_tmp9_ = start;
	if (_tmp9_ >= ((glong) 0)) {
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp10_ = start;
		_tmp11_ = string_length;
		_tmp8_ = _tmp10_ <= _tmp11_;
	} else {
		_tmp8_ = FALSE;
	}
	g_return_val_if_fail (_tmp8_, NULL);
	_tmp13_ = end;
	if (_tmp13_ >= ((glong) 0)) {
		glong _tmp14_ = 0L;
		glong _tmp15_ = 0L;
		_tmp14_ = end;
		_tmp15_ = string_length;
		_tmp12_ = _tmp14_ <= _tmp15_;
	} else {
		_tmp12_ = FALSE;
	}
	g_return_val_if_fail (_tmp12_, NULL);
	_tmp16_ = start;
	_tmp17_ = end;
	g_return_val_if_fail (_tmp16_ <= _tmp17_, NULL);
	_tmp18_ = start;
	_tmp19_ = end;
	_tmp20_ = start;
	_tmp21_ = g_strndup (((gchar*) self) + _tmp18_, (gsize) (_tmp19_ - _tmp20_));
	result = _tmp21_;
	return result;
}


SoupMessage* oauth_zenmoney_Auth (OauthZenmoney* self, const gchar* method, const gchar* url, GeeMultiMap* parameters) {
	SoupMessage* result = NULL;
	gchar* myurl = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GeeMultiMap* _tmp2_ = NULL;
	const gchar* _tmp39_ = NULL;
	gchar* _tmp40_ = NULL;
	gchar* _tmp41_ = NULL;
	SoupMessage* message = NULL;
	const gchar* _tmp42_ = NULL;
	const gchar* _tmp43_ = NULL;
	SoupMessage* _tmp44_ = NULL;
	gchar* oauth_header = NULL;
	OAuthClient* _tmp45_ = NULL;
	const gchar* _tmp46_ = NULL;
	const gchar* _tmp47_ = NULL;
	GeeMultiMap* _tmp48_ = NULL;
	GeeMap* _tmp49_ = NULL;
	GeeMap* _tmp50_ = NULL;
	gpointer _tmp51_ = NULL;
	gchar* _tmp52_ = NULL;
	SoupMessageHeaders* _tmp53_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (method != NULL, NULL);
	g_return_val_if_fail (url != NULL, NULL);
	_tmp0_ = url;
	_tmp1_ = g_strdup (_tmp0_);
	myurl = _tmp1_;
	_tmp2_ = parameters;
	if (_tmp2_ != NULL) {
		const gchar* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		const gchar* _tmp34_ = NULL;
		const gchar* _tmp35_ = NULL;
		gint _tmp36_ = 0;
		gint _tmp37_ = 0;
		gchar* _tmp38_ = NULL;
		_tmp3_ = myurl;
		_tmp4_ = g_strconcat (_tmp3_, "?", NULL);
		_g_free0 (myurl);
		myurl = _tmp4_;
		{
			GeeIterator* _key_it = NULL;
			GeeMultiMap* _tmp5_ = NULL;
			GeeSet* _tmp6_ = NULL;
			GeeSet* _tmp7_ = NULL;
			GeeIterator* _tmp8_ = NULL;
			GeeIterator* _tmp9_ = NULL;
			_tmp5_ = parameters;
			_tmp6_ = gee_multi_map_get_keys (_tmp5_);
			_tmp7_ = _tmp6_;
			_tmp8_ = gee_iterable_iterator ((GeeIterable*) _tmp7_);
			_tmp9_ = _tmp8_;
			_g_object_unref0 (_tmp7_);
			_key_it = _tmp9_;
			while (TRUE) {
				GeeIterator* _tmp10_ = NULL;
				gboolean _tmp11_ = FALSE;
				gchar* key = NULL;
				GeeIterator* _tmp12_ = NULL;
				gpointer _tmp13_ = NULL;
				_tmp10_ = _key_it;
				_tmp11_ = gee_iterator_next (_tmp10_);
				if (!_tmp11_) {
					break;
				}
				_tmp12_ = _key_it;
				_tmp13_ = gee_iterator_get (_tmp12_);
				key = (gchar*) _tmp13_;
				{
					GeeIterator* _value_it = NULL;
					GeeMultiMap* _tmp14_ = NULL;
					const gchar* _tmp15_ = NULL;
					GeeCollection* _tmp16_ = NULL;
					GeeCollection* _tmp17_ = NULL;
					GeeIterator* _tmp18_ = NULL;
					GeeIterator* _tmp19_ = NULL;
					_tmp14_ = parameters;
					_tmp15_ = key;
					_tmp16_ = gee_multi_map_get (_tmp14_, _tmp15_);
					_tmp17_ = _tmp16_;
					_tmp18_ = gee_iterable_iterator ((GeeIterable*) _tmp17_);
					_tmp19_ = _tmp18_;
					_g_object_unref0 (_tmp17_);
					_value_it = _tmp19_;
					while (TRUE) {
						GeeIterator* _tmp20_ = NULL;
						gboolean _tmp21_ = FALSE;
						gchar* value = NULL;
						GeeIterator* _tmp22_ = NULL;
						gpointer _tmp23_ = NULL;
						const gchar* _tmp24_ = NULL;
						const gchar* _tmp25_ = NULL;
						gchar* _tmp26_ = NULL;
						gchar* _tmp27_ = NULL;
						const gchar* _tmp28_ = NULL;
						gchar* _tmp29_ = NULL;
						gchar* _tmp30_ = NULL;
						gchar* _tmp31_ = NULL;
						gchar* _tmp32_ = NULL;
						gchar* _tmp33_ = NULL;
						_tmp20_ = _value_it;
						_tmp21_ = gee_iterator_next (_tmp20_);
						if (!_tmp21_) {
							break;
						}
						_tmp22_ = _value_it;
						_tmp23_ = gee_iterator_get (_tmp22_);
						value = (gchar*) _tmp23_;
						_tmp24_ = myurl;
						_tmp25_ = key;
						_tmp26_ = g_strconcat (_tmp25_, "=", NULL);
						_tmp27_ = _tmp26_;
						_tmp28_ = value;
						_tmp29_ = g_strconcat (_tmp27_, _tmp28_, NULL);
						_tmp30_ = _tmp29_;
						_tmp31_ = g_strconcat (_tmp30_, "&", NULL);
						_tmp32_ = _tmp31_;
						_tmp33_ = g_strconcat (_tmp24_, _tmp32_, NULL);
						_g_free0 (myurl);
						myurl = _tmp33_;
						_g_free0 (_tmp32_);
						_g_free0 (_tmp30_);
						_g_free0 (_tmp27_);
						_g_free0 (value);
					}
					_g_object_unref0 (_value_it);
				}
				_g_free0 (key);
			}
			_g_object_unref0 (_key_it);
		}
		_tmp34_ = myurl;
		_tmp35_ = myurl;
		_tmp36_ = strlen (_tmp35_);
		_tmp37_ = _tmp36_;
		_tmp38_ = string_slice (_tmp34_, (glong) 0, (glong) (_tmp37_ - 1));
		_g_free0 (myurl);
		myurl = _tmp38_;
	}
	_tmp39_ = myurl;
	_tmp40_ = g_strconcat (_tmp39_, "\n", NULL);
	_tmp41_ = _tmp40_;
	g_print ("%s", _tmp41_);
	_g_free0 (_tmp41_);
	_tmp42_ = method;
	_tmp43_ = myurl;
	_tmp44_ = soup_message_new (_tmp42_, _tmp43_);
	message = _tmp44_;
	_tmp45_ = self->priv->client;
	_tmp46_ = method;
	_tmp47_ = url;
	_tmp48_ = parameters;
	_tmp49_ = oauth_client_authenticate (_tmp45_, _tmp46_, _tmp47_, _tmp48_);
	_tmp50_ = _tmp49_;
	_tmp51_ = gee_map_get (_tmp50_, "Authorization");
	_tmp52_ = (gchar*) _tmp51_;
	_g_object_unref0 (_tmp50_);
	oauth_header = _tmp52_;
	_tmp53_ = message->request_headers;
	soup_message_headers_append (_tmp53_, "Authorization", oauth_header);
	result = message;
	_g_free0 (oauth_header);
	_g_free0 (myurl);
	return result;
}


static void value_oauth_zenmoney_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_oauth_zenmoney_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		oauth_zenmoney_unref (value->data[0].v_pointer);
	}
}


static void value_oauth_zenmoney_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = oauth_zenmoney_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_oauth_zenmoney_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_oauth_zenmoney_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		OauthZenmoney* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = oauth_zenmoney_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_oauth_zenmoney_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	OauthZenmoney** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = oauth_zenmoney_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_oauth_zenmoney (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecOauthZenmoney* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_OAUTH_ZENMONEY), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_oauth_zenmoney (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_OAUTH_ZENMONEY), NULL);
	return value->data[0].v_pointer;
}


void value_set_oauth_zenmoney (GValue* value, gpointer v_object) {
	OauthZenmoney* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_OAUTH_ZENMONEY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_OAUTH_ZENMONEY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		oauth_zenmoney_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		oauth_zenmoney_unref (old);
	}
}


void value_take_oauth_zenmoney (GValue* value, gpointer v_object) {
	OauthZenmoney* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_OAUTH_ZENMONEY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_OAUTH_ZENMONEY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		oauth_zenmoney_unref (old);
	}
}


static void oauth_zenmoney_class_init (OauthZenmoneyClass * klass) {
	oauth_zenmoney_parent_class = g_type_class_peek_parent (klass);
	((OauthZenmoneyClass *) klass)->finalize = oauth_zenmoney_finalize;
	g_type_class_add_private (klass, sizeof (OauthZenmoneyPrivate));
}


static void oauth_zenmoney_instance_init (OauthZenmoney * self) {
	gchar* _tmp0_ = NULL;
	self->priv = OAUTH_ZENMONEY_GET_PRIVATE (self);
	_tmp0_ = g_strdup ("");
	self->priv->token = _tmp0_;
	self->ref_count = 1;
}


static void oauth_zenmoney_finalize (OauthZenmoney* obj) {
	OauthZenmoney * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_OAUTH_ZENMONEY, OauthZenmoney);
	g_signal_handlers_destroy (self);
	_g_object_unref0 (self->priv->client);
	_g_free0 (self->priv->token);
}


GType oauth_zenmoney_get_type (void) {
	static volatile gsize oauth_zenmoney_type_id__volatile = 0;
	if (g_once_init_enter (&oauth_zenmoney_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_oauth_zenmoney_init, value_oauth_zenmoney_free_value, value_oauth_zenmoney_copy_value, value_oauth_zenmoney_peek_pointer, "p", value_oauth_zenmoney_collect_value, "p", value_oauth_zenmoney_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (OauthZenmoneyClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) oauth_zenmoney_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OauthZenmoney), 0, (GInstanceInitFunc) oauth_zenmoney_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType oauth_zenmoney_type_id;
		oauth_zenmoney_type_id = g_type_register_fundamental (g_type_fundamental_next (), "OauthZenmoney", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&oauth_zenmoney_type_id__volatile, oauth_zenmoney_type_id);
	}
	return oauth_zenmoney_type_id__volatile;
}


gpointer oauth_zenmoney_ref (gpointer instance) {
	OauthZenmoney* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void oauth_zenmoney_unref (gpointer instance) {
	OauthZenmoney* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		OAUTH_ZENMONEY_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



