/* zenmoney.c generated by valac 0.28.1, the Vala compiler
 * generated from zenmoney.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <json-glib/json-glib.h>
#include <libsoup/soup.h>
#include <gobject/gvaluecollector.h>


#define TYPE_ZENMONEY (zenmoney_get_type ())
#define ZENMONEY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ZENMONEY, Zenmoney))
#define ZENMONEY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ZENMONEY, ZenmoneyClass))
#define IS_ZENMONEY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ZENMONEY))
#define IS_ZENMONEY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ZENMONEY))
#define ZENMONEY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ZENMONEY, ZenmoneyClass))

typedef struct _Zenmoney Zenmoney;
typedef struct _ZenmoneyClass ZenmoneyClass;
typedef struct _ZenmoneyPrivate ZenmoneyPrivate;

#define TYPE_OAUTH_ZENMONEY (oauth_zenmoney_get_type ())
#define OAUTH_ZENMONEY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OAUTH_ZENMONEY, OauthZenmoney))
#define OAUTH_ZENMONEY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_OAUTH_ZENMONEY, OauthZenmoneyClass))
#define IS_OAUTH_ZENMONEY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OAUTH_ZENMONEY))
#define IS_OAUTH_ZENMONEY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_OAUTH_ZENMONEY))
#define OAUTH_ZENMONEY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_OAUTH_ZENMONEY, OauthZenmoneyClass))

typedef struct _OauthZenmoney OauthZenmoney;
typedef struct _OauthZenmoneyClass OauthZenmoneyClass;
#define _oauth_zenmoney_unref0(var) ((var == NULL) ? NULL : (var = (oauth_zenmoney_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define __vala_SoupBuffer_free0(var) ((var == NULL) ? NULL : (var = (_vala_SoupBuffer_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ParamSpecZenmoney ParamSpecZenmoney;

struct _Zenmoney {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ZenmoneyPrivate * priv;
};

struct _ZenmoneyClass {
	GTypeClass parent_class;
	void (*finalize) (Zenmoney *self);
};

struct _ZenmoneyPrivate {
	OauthZenmoney* ot;
};

struct _ParamSpecZenmoney {
	GParamSpec parent_instance;
};


static gpointer zenmoney_parent_class = NULL;

#define OWNER_INFO_URL "http://api.zenmoney.ru/v1/owner/"
gpointer zenmoney_ref (gpointer instance);
void zenmoney_unref (gpointer instance);
GParamSpec* param_spec_zenmoney (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_zenmoney (GValue* value, gpointer v_object);
void value_take_zenmoney (GValue* value, gpointer v_object);
gpointer value_get_zenmoney (const GValue* value);
GType zenmoney_get_type (void) G_GNUC_CONST;
gpointer oauth_zenmoney_ref (gpointer instance);
void oauth_zenmoney_unref (gpointer instance);
GParamSpec* param_spec_oauth_zenmoney (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_oauth_zenmoney (GValue* value, gpointer v_object);
void value_take_oauth_zenmoney (GValue* value, gpointer v_object);
gpointer value_get_oauth_zenmoney (const GValue* value);
GType oauth_zenmoney_get_type (void) G_GNUC_CONST;
#define ZENMONEY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_ZENMONEY, ZenmoneyPrivate))
enum  {
	ZENMONEY_DUMMY_PROPERTY
};
Zenmoney* zenmoney_new (void);
Zenmoney* zenmoney_construct (GType object_type);
OauthZenmoney* oauth_zenmoney_new (void);
OauthZenmoney* oauth_zenmoney_construct (GType object_type);
void zenmoney_init (Zenmoney* self, const gchar* token, const gchar* token_secret);
void oauth_zenmoney_init (OauthZenmoney* self, const gchar* token, const gchar* token_secret);
void zenmoney_getAccessToken_A (Zenmoney* self);
void oauth_zenmoney_getAccessToken_A (OauthZenmoney* self);
GeeMap* zenmoney_getAccessToken_B (Zenmoney* self, const gchar* pin);
GeeMap* oauth_zenmoney_getAccessToken_B (OauthZenmoney* self, const gchar* pin);
JsonParser* zenmoney_home_timeline (Zenmoney* self);
SoupMessage* oauth_zenmoney_Auth (OauthZenmoney* self, const gchar* method, const gchar* url, GeeMultiMap* parameters);
static void _vala_SoupBuffer_free (SoupBuffer* self);
static void zenmoney_finalize (Zenmoney* obj);


Zenmoney* zenmoney_construct (GType object_type) {
	Zenmoney* self = NULL;
	OauthZenmoney* _tmp0_ = NULL;
	self = (Zenmoney*) g_type_create_instance (object_type);
	g_print ("New Zenmoney /n");
	_tmp0_ = oauth_zenmoney_new ();
	_oauth_zenmoney_unref0 (self->priv->ot);
	self->priv->ot = _tmp0_;
	return self;
}


Zenmoney* zenmoney_new (void) {
	return zenmoney_construct (TYPE_ZENMONEY);
}


void zenmoney_init (Zenmoney* self, const gchar* token, const gchar* token_secret) {
	OauthZenmoney* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (token != NULL);
	g_return_if_fail (token_secret != NULL);
	_tmp0_ = self->priv->ot;
	_tmp1_ = token;
	_tmp2_ = token_secret;
	oauth_zenmoney_init (_tmp0_, _tmp1_, _tmp2_);
}


void zenmoney_getAccessToken_A (Zenmoney* self) {
	OauthZenmoney* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->ot;
	oauth_zenmoney_getAccessToken_A (_tmp0_);
}


GeeMap* zenmoney_getAccessToken_B (Zenmoney* self, const gchar* pin) {
	GeeMap* result = NULL;
	OauthZenmoney* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GeeMap* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (pin != NULL, NULL);
	_tmp0_ = self->priv->ot;
	_tmp1_ = pin;
	_tmp2_ = oauth_zenmoney_getAccessToken_B (_tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


static void _vala_SoupBuffer_free (SoupBuffer* self) {
	g_boxed_free (soup_buffer_get_type (), self);
}


JsonParser* zenmoney_home_timeline (Zenmoney* self) {
	JsonParser* result = NULL;
	SoupSession* session = NULL;
	SoupSessionAsync* _tmp0_ = NULL;
	SoupMessage* message = NULL;
	OauthZenmoney* _tmp1_ = NULL;
	SoupMessage* _tmp2_ = NULL;
	JsonParser* parser = NULL;
	JsonParser* _tmp3_ = NULL;
	SoupMessageBody* _tmp20_ = NULL;
	SoupBuffer* _tmp21_ = NULL;
	SoupBuffer* _tmp22_ = NULL;
	guint8* _tmp23_ = NULL;
	gint _tmp23__length1 = 0;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_print ("Home_timeline /n");
	_tmp0_ = (SoupSessionAsync*) soup_session_async_new ();
	session = (SoupSession*) _tmp0_;
	_tmp1_ = self->priv->ot;
	_tmp2_ = oauth_zenmoney_Auth (_tmp1_, "POST", OWNER_INFO_URL, NULL);
	message = _tmp2_;
	soup_session_send_message (session, message);
	_tmp3_ = json_parser_new ();
	parser = _tmp3_;
	{
		SoupMessageBody* _tmp4_ = NULL;
		SoupBuffer* _tmp5_ = NULL;
		SoupBuffer* _tmp6_ = NULL;
		guint8* _tmp7_ = NULL;
		gint _tmp7__length1 = 0;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		SoupMessageBody* _tmp12_ = NULL;
		SoupBuffer* _tmp13_ = NULL;
		SoupBuffer* _tmp14_ = NULL;
		guint8* _tmp15_ = NULL;
		gint _tmp15__length1 = 0;
		_tmp4_ = message->response_body;
		_tmp5_ = soup_message_body_flatten (_tmp4_);
		_tmp6_ = _tmp5_;
		_tmp7_ = _tmp6_->data;
		_tmp7__length1 = (gint) _tmp6_->length;
		_tmp8_ = g_strconcat ("response: ", (const gchar*) _tmp7_, NULL);
		_tmp9_ = _tmp8_;
		_tmp10_ = g_strconcat (_tmp9_, "\n", NULL);
		_tmp11_ = _tmp10_;
		g_print ("%s", _tmp11_);
		_g_free0 (_tmp11_);
		_g_free0 (_tmp9_);
		__vala_SoupBuffer_free0 (_tmp6_);
		_tmp12_ = message->response_body;
		_tmp13_ = soup_message_body_flatten (_tmp12_);
		_tmp14_ = _tmp13_;
		_tmp15_ = _tmp14_->data;
		_tmp15__length1 = (gint) _tmp14_->length;
		json_parser_load_from_data (parser, (const gchar*) _tmp15_, (gssize) (-1), &_inner_error_);
		__vala_SoupBuffer_free0 (_tmp14_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch5_g_error;
		}
	}
	goto __finally5;
	__catch5_g_error:
	{
		GError* e = NULL;
		GError* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
		gchar* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp16_ = e;
		_tmp17_ = _tmp16_->message;
		_tmp18_ = g_strconcat ("Error: ", _tmp17_, NULL);
		_tmp19_ = _tmp18_;
		g_print ("%s", _tmp19_);
		_g_free0 (_tmp19_);
		_g_error_free0 (e);
	}
	__finally5:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (parser);
		_g_object_unref0 (message);
		_g_object_unref0 (session);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp20_ = message->response_body;
	_tmp21_ = soup_message_body_flatten (_tmp20_);
	_tmp22_ = _tmp21_;
	_tmp23_ = _tmp22_->data;
	_tmp23__length1 = (gint) _tmp22_->length;
	_tmp24_ = g_strconcat ("response", (const gchar*) _tmp23_, NULL);
	_tmp25_ = _tmp24_;
	g_print ("%s", _tmp25_);
	_g_free0 (_tmp25_);
	__vala_SoupBuffer_free0 (_tmp22_);
	result = parser;
	_g_object_unref0 (message);
	_g_object_unref0 (session);
	return result;
}


static void value_zenmoney_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_zenmoney_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		zenmoney_unref (value->data[0].v_pointer);
	}
}


static void value_zenmoney_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = zenmoney_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_zenmoney_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_zenmoney_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		Zenmoney* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = zenmoney_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_zenmoney_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	Zenmoney** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = zenmoney_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_zenmoney (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecZenmoney* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_ZENMONEY), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_zenmoney (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_ZENMONEY), NULL);
	return value->data[0].v_pointer;
}


void value_set_zenmoney (GValue* value, gpointer v_object) {
	Zenmoney* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_ZENMONEY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_ZENMONEY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		zenmoney_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		zenmoney_unref (old);
	}
}


void value_take_zenmoney (GValue* value, gpointer v_object) {
	Zenmoney* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_ZENMONEY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_ZENMONEY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		zenmoney_unref (old);
	}
}


static void zenmoney_class_init (ZenmoneyClass * klass) {
	zenmoney_parent_class = g_type_class_peek_parent (klass);
	((ZenmoneyClass *) klass)->finalize = zenmoney_finalize;
	g_type_class_add_private (klass, sizeof (ZenmoneyPrivate));
}


static void zenmoney_instance_init (Zenmoney * self) {
	self->priv = ZENMONEY_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void zenmoney_finalize (Zenmoney* obj) {
	Zenmoney * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_ZENMONEY, Zenmoney);
	g_signal_handlers_destroy (self);
	_oauth_zenmoney_unref0 (self->priv->ot);
}


GType zenmoney_get_type (void) {
	static volatile gsize zenmoney_type_id__volatile = 0;
	if (g_once_init_enter (&zenmoney_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_zenmoney_init, value_zenmoney_free_value, value_zenmoney_copy_value, value_zenmoney_peek_pointer, "p", value_zenmoney_collect_value, "p", value_zenmoney_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ZenmoneyClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) zenmoney_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Zenmoney), 0, (GInstanceInitFunc) zenmoney_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType zenmoney_type_id;
		zenmoney_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Zenmoney", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&zenmoney_type_id__volatile, zenmoney_type_id);
	}
	return zenmoney_type_id__volatile;
}


gpointer zenmoney_ref (gpointer instance) {
	Zenmoney* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void zenmoney_unref (gpointer instance) {
	Zenmoney* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		ZENMONEY_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



